// <auto-generated />
using System;
using CelebrateHub.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CelebrateHub.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CelebrateHub.Data.Models.Employee", b =>
                {
                    b.Property<int>("EmployeeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("EmployeeId"));

                    b.Property<DateTime?>("AnniversaryDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateOfBirth")
                        .HasColumnType("datetime2");

                    b.Property<string>("Department")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Project")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("EmployeeId");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Employees");

                    b.HasData(
                        new
                        {
                            EmployeeId = 1,
                            AnniversaryDate = new DateTime(2018, 3, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedDate = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateOfBirth = new DateTime(1990, 6, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Department = "IT",
                            Email = "admin@portal.com",
                            IsActive = true,
                            Name = "Admin User",
                            PasswordHash = "$2a$11$CQsKloLgaA9GRRtcPnfxpee8lmuk.RCJhIdwg6CtLJ6vDN6iaL5.m",
                            Role = "Admin"
                        });
                });

            modelBuilder.Entity("CelebrateHub.Data.Models.PartyEvent", b =>
                {
                    b.Property<int>("PartyEventId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PartyEventId"));

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("DonePercentage")
                        .HasColumnType("decimal(5,2)");

                    b.Property<int>("DoneVotes")
                        .HasColumnType("int");

                    b.Property<int>("EmployeeId")
                        .HasColumnType("int");

                    b.Property<DateTime>("EventDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<int>("PendingVotes")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("TotalVotes")
                        .HasColumnType("int");

                    b.HasKey("PartyEventId");

                    b.HasIndex("EmployeeId", "EventType", "EventDate")
                        .IsUnique();

                    b.ToTable("PartyEvents");

                    b.HasData(
                        new
                        {
                            PartyEventId = 1,
                            CreatedDate = new DateTime(2025, 6, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DonePercentage = 0m,
                            DoneVotes = 0,
                            EmployeeId = 1,
                            EventDate = new DateTime(2025, 6, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EventType = "Birthday",
                            IsActive = true,
                            PendingVotes = 0,
                            Status = "Pending",
                            TotalVotes = 0
                        },
                        new
                        {
                            PartyEventId = 2,
                            CreatedDate = new DateTime(2025, 3, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DonePercentage = 0m,
                            DoneVotes = 0,
                            EmployeeId = 1,
                            EventDate = new DateTime(2025, 3, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EventType = "Anniversary",
                            IsActive = true,
                            PendingVotes = 0,
                            Status = "Pending",
                            TotalVotes = 0
                        });
                });

            modelBuilder.Entity("CelebrateHub.Data.Models.PartyVote", b =>
                {
                    b.Property<int>("PartyVoteId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PartyVoteId"));

                    b.Property<int>("PartyEventId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("VoteType")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<DateTime>("VotedOn")
                        .HasColumnType("datetime2");

                    b.Property<int>("VoterEmployeeId")
                        .HasColumnType("int");

                    b.HasKey("PartyVoteId");

                    b.HasIndex("VoterEmployeeId");

                    b.HasIndex("PartyEventId", "VoterEmployeeId")
                        .IsUnique();

                    b.ToTable("PartyVotes");
                });

            modelBuilder.Entity("CelebrateHub.Data.Models.PartyEvent", b =>
                {
                    b.HasOne("CelebrateHub.Data.Models.Employee", "Employee")
                        .WithMany()
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Employee");
                });

            modelBuilder.Entity("CelebrateHub.Data.Models.PartyVote", b =>
                {
                    b.HasOne("CelebrateHub.Data.Models.PartyEvent", "PartyEvent")
                        .WithMany("Votes")
                        .HasForeignKey("PartyEventId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CelebrateHub.Data.Models.Employee", "VoterEmployee")
                        .WithMany()
                        .HasForeignKey("VoterEmployeeId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("PartyEvent");

                    b.Navigation("VoterEmployee");
                });

            modelBuilder.Entity("CelebrateHub.Data.Models.PartyEvent", b =>
                {
                    b.Navigation("Votes");
                });
#pragma warning restore 612, 618
        }
    }
}
